2024-11-10 23:47:10,125 - INFO - Extractores disponíveis: pypdf2, pdfplumber, pdfminer, tesseract, pdf2image
2024-11-10 23:47:10,125 - INFO - Suporte a OCR está disponível
2024-11-10 23:47:10,128 - INFO - Encontrados 12 arquivos PDF para processar
2024-11-10 23:47:10,128 - INFO - Processing: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-10 23:47:10,128 - INFO - Processing: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-10 23:47:10,128 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-10 23:47:10,128 - INFO - Processing: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-10 23:47:10,129 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-10 23:47:10,129 - INFO - Processing: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-10 23:47:10,129 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-10 23:47:10,129 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-10 23:47:10,156 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:47:10,156 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:47:10,157 - INFO - Extraindo metadados de: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-10 23:47:10,242 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:47:10,243 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:47:10,243 - INFO - Extraindo metadados de: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-10 23:47:10,256 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:47:10,256 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:47:10,256 - INFO - Extraindo metadados de: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-10 23:47:10,277 - INFO - Processing: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-10 23:47:10,277 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-10 23:47:10,286 - WARNING - Sem metadados: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-10 23:47:10,319 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:47:10,319 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:47:10,319 - INFO - Extraindo metadados de: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-10 23:47:10,629 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:47:10,629 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:47:10,630 - INFO - Extraindo metadados de: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-10 23:47:43,797 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781119895237/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:47:44,081 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586593181/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:47:44,192 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586110364/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:47:44,272 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781718501553/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:48:15,216 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781119895237/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:48:15,371 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586110364/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:48:15,427 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781718501553/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:48:15,439 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586593181/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:48:46,346 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586110364/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:48:46,442 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781718501553/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:48:46,629 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586593181/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:48:47,106 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781119895237/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:48:47,268 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586110364
2024-11-10 23:48:47,367 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781718501553
2024-11-10 23:48:47,492 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586110364
2024-11-10 23:48:47,543 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586593181
2024-11-10 23:48:47,593 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781718501553
2024-11-10 23:48:47,716 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586110364
2024-11-10 23:48:47,770 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586593181
2024-11-10 23:48:47,815 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781718501553
2024-11-10 23:48:47,993 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586593181
2024-11-10 23:48:48,016 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781119895237
2024-11-10 23:48:48,239 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781119895237
2024-11-10 23:48:48,463 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781119895237
2024-11-10 23:48:56,562 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403448b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:48:57,455 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104d8f040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:48:57,568 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140344c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:48:58,148 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14055e880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:48:58,463 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14055e670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:48:59,155 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140556070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:48:59,576 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14055ef40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:48:59,924 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141808250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:00,466 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141808670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:49:00,931 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1405ed130>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:01,161 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141808fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:49:02,940 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140556dc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:03,585 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141808d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:49:04,476 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140556f70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:49:05,167 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140556c10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:49:06,944 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140556940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:11,595 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140556850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:49:11,598 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781718501553 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14055e310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:11,605 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14055e2b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:49:12,484 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1405566a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:49:12,489 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9786586110364 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140556850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:12,496 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141808d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:49:12,613 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14055eb80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:49:13,175 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140556490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:49:13,180 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9786586593181 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140553ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:13,185 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140553880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:49:13,503 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140553df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:49:14,192 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140553520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:49:14,622 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140553cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:49:14,953 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14055ec10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:14,958 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781119895237 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140341e20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:14,965 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140341c40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:15,509 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1405533d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:49:15,972 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140341970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:16,201 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1405531f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:49:17,981 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403415b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:18,630 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403417f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:49:19,519 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403416a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:49:20,210 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140341400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:49:21,993 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403411f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:26,640 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1402c54c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781718501553
2024-11-10 23:49:26,644 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781718501553 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403b69d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:27,527 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1404e2cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110364
2024-11-10 23:49:27,532 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9786586110364 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403b6430>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:27,896 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14033bb20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781718501553
2024-11-10 23:49:28,218 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403b6f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586593181
2024-11-10 23:49:28,223 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9786586593181 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14033b4c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:28,905 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14033b160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781718501553
2024-11-10 23:49:29,171 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14033be80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110364
2024-11-10 23:49:29,172 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140371730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586593181
2024-11-10 23:49:30,002 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403b6b80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895237
2024-11-10 23:49:30,006 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781119895237 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140371b80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:30,178 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403716d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110364
2024-11-10 23:49:30,178 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140371970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586593181
2024-11-10 23:49:30,914 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403712b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781718501553
2024-11-10 23:49:30,975 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403711f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895237
2024-11-10 23:49:31,981 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140371fa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895237
2024-11-10 23:49:32,185 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140371e20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110364
2024-11-10 23:49:32,185 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140252940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586593181
2024-11-10 23:49:33,990 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140275bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895237
2024-11-10 23:49:34,923 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403b6cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781718501553
2024-11-10 23:49:36,191 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140344580>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586593181
2024-11-10 23:49:36,194 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140344d60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110364
2024-11-10 23:49:38,001 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403441f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895237
2024-11-10 23:49:42,932 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140344a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781718501553
2024-11-10 23:49:42,936 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781718501553 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14058ae80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:44,200 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140344430>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586593181
2024-11-10 23:49:44,201 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140344490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110364
2024-11-10 23:49:44,205 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9786586593181 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14058a880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:44,206 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9786586110364 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14058a0a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:46,009 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140378f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895237
2024-11-10 23:49:46,013 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781119895237 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1403b6a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:49:59,289 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781718501553 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:00,356 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9786586593181 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:00,806 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9786586110364 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:02,124 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781119895237 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:17,569 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781718501553 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:17,570 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9786586593181 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:17,577 - INFO - Processing: /Users/menon/Downloads/bashcookbook.pdf
2024-11-10 23:50:17,578 - INFO - Sucesso: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-10 23:50:17,578 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/bashcookbook.pdf
2024-11-10 23:50:17,580 - INFO - Processing: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-10 23:50:17,580 - INFO - Sucesso: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-10 23:50:17,580 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-10 23:50:17,634 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:50:17,641 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:50:17,647 - INFO - Extraindo metadados de: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-10 23:50:17,667 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:50:17,667 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:50:17,674 - INFO - Extraindo metadados de: /Users/menon/Downloads/bashcookbook.pdf
2024-11-10 23:50:17,681 - INFO - Processing: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-10 23:50:17,681 - WARNING - Sem metadados: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-10 23:50:17,682 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-10 23:50:17,749 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:50:17,749 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:50:17,749 - INFO - Extraindo metadados de: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-10 23:50:18,082 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9786586110364 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:18,085 - INFO - Processing: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-10 23:50:18,086 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-10 23:50:18,086 - INFO - Sucesso: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-10 23:50:18,181 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:50:18,181 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:50:18,181 - INFO - Extraindo metadados de: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-10 23:50:18,198 - INFO - Processing: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-10 23:50:18,198 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-10 23:50:18,198 - WARNING - Sem metadados: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-10 23:50:18,230 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:50:18,230 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:50:18,230 - INFO - Extraindo metadados de: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-10 23:50:18,750 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781119895237 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:18,755 - INFO - Processing: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-10 23:50:18,755 - INFO - Sucesso: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-10 23:50:18,755 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-10 23:50:18,867 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:50:18,867 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:50:18,868 - INFO - Extraindo metadados de: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-10 23:50:18,885 - INFO - Processing: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-10 23:50:18,885 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-10 23:50:18,885 - WARNING - Sem metadados: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-10 23:50:19,062 - INFO - Métodos tentados: PyPDF2
2024-11-10 23:50:19,062 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-10 23:50:19,063 - INFO - Extraindo metadados de: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-10 23:50:51,172 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781593278748/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:51,186 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781492056119/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:51,434 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781491975336/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:50:53,224 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9788575227510/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:51:22,595 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781593278748/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:51:22,606 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781492056119/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:51:22,803 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781491975336/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:51:24,178 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9788575227510/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:51:53,686 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781492056119/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:51:54,379 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781491975336/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:51:54,472 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781593278748/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:51:54,668 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781492056119
2024-11-10 23:51:54,948 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781492056119
2024-11-10 23:51:55,172 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781492056119
2024-11-10 23:51:55,296 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781491975336
2024-11-10 23:51:55,393 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781593278748
2024-11-10 23:51:55,439 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9788575227510/ (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:51:55,523 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781491975336
2024-11-10 23:51:55,618 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781593278748
2024-11-10 23:51:55,664 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9788575227510
2024-11-10 23:51:55,748 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781491975336
2024-11-10 23:51:55,845 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781593278748
2024-11-10 23:51:55,888 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9788575227510
2024-11-10 23:51:56,111 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9788575227510
2024-11-10 23:52:06,612 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b1ad90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:52:07,368 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a23220>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:52:07,505 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140275a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:52:07,620 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a23b50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:52:08,380 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14033b400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:52:08,512 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14033b5e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:52:09,628 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14058a550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:52:10,242 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b253d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:52:10,397 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x140275c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:52:10,517 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141ac87c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:52:11,254 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a765b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:52:13,267 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a76b50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:52:13,633 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141ac88e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:52:14,405 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a767f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:52:14,522 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a769a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:52:17,281 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a76d00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:52:21,646 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a76eb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:52:21,662 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781491975336 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a515b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:52:21,669 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a51700>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:52:22,409 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a510a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:52:22,412 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781492056119 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a51bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:52:22,417 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a51d00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:52:22,529 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a51250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:52:22,531 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9788575227510 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6e1f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:52:22,535 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6e340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:52:22,680 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a51a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:52:23,429 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6e040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:52:23,548 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6e640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:52:24,685 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a51250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:52:25,288 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a51400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:52:25,292 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781593278748 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a767f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:52:25,298 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6e730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:52:25,443 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a51130>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:52:25,554 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a76730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:52:26,302 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6ea90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:55:23,081 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6efa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:55:23,459 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a76ee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:55:24,222 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6ec40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:55:24,334 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6edf0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:55:27,828 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:55:31,828 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491975336
2024-11-10 23:55:31,834 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781491975336 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:55:32,982 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b374f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781492056119
2024-11-10 23:55:32,985 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9788575227510
2024-11-10 23:55:32,987 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781492056119 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:55:32,988 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9788575227510 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:55:34,471 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /books/v1/volumes?q=isbn%3A9781492056119&country=BR&langRestrict=pt
2024-11-10 23:55:34,474 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /books/v1/volumes?q=isbn%3A9788575227510&country=BR&langRestrict=pt
2024-11-10 23:55:36,859 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278748
2024-11-10 23:55:36,863 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781593278748 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:55:38,352 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b2ca30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278748
2024-11-10 23:55:38,353 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b2c100>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9788575227510
2024-11-10 23:55:38,353 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1402996d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781492056119
2024-11-10 23:55:38,353 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b2c880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491975336
2024-11-10 23:55:39,358 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b2ce80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781492056119
2024-11-10 23:55:39,359 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b2cfa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491975336
2024-11-10 23:55:39,359 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b2cd60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9788575227510
2024-11-10 23:55:39,365 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b2cc40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278748
2024-11-10 23:55:41,369 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b00520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9788575227510
2024-11-10 23:55:41,372 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b002e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781492056119
2024-11-10 23:55:41,372 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b00400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491975336
2024-11-10 23:55:41,376 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a76a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278748
2024-11-10 23:55:45,375 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141856550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9788575227510
2024-11-10 23:55:45,383 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b376d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278748
2024-11-10 23:55:45,384 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6ed90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781492056119
2024-11-10 23:55:45,384 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141a6ef10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491975336
2024-11-10 23:55:53,390 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b372b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9788575227510
2024-11-10 23:55:53,391 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491975336
2024-11-10 23:55:53,391 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278748
2024-11-10 23:55:53,391 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b37fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781492056119
2024-11-10 23:55:53,396 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9788575227510 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b009a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:55:53,396 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781593278748 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b00c40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:55:53,396 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781491975336 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b00ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:55:53,396 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781492056119 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x141b00d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-10 23:56:32,531 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /api/v1/references?q=9781491975336
2024-11-10 23:56:32,555 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /api/v1/references?q=9781492056119
2024-11-10 23:56:42,333 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.mybib.com', port=443): Read timed out. (read timeout=10)")': /api/v1/references?q=9788575227510
2024-11-10 23:56:42,435 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.mybib.com', port=443): Read timed out. (read timeout=10)")': /api/v1/references?q=9781593278748
2024-11-10 23:56:58,887 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781491975336 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:56:58,889 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781492056119 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:56:59,427 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781593278748 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:56:59,460 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9788575227510 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:57:18,856 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781593278748 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:57:18,861 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9788575227510 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:57:18,862 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781491975336 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:57:18,870 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781492056119 (Caused by ResponseError('too many 404 error responses'))
2024-11-10 23:57:18,870 - INFO - Sucesso: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-10 23:57:18,875 - INFO - Sucesso: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-10 23:57:18,876 - INFO - Sucesso: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-10 23:57:18,877 - INFO - Sucesso: /Users/menon/Downloads/bashcookbook.pdf
2024-11-11 00:19:27,073 - INFO - Extractores disponíveis: pypdf2, pdfplumber, pdfminer, tesseract, pdf2image
2024-11-11 00:19:27,074 - INFO - Suporte a OCR está disponível
2024-11-11 00:19:27,075 - INFO - Encontrados 12 arquivos PDF para processar
2024-11-11 00:19:27,075 - INFO - Processing: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-11 00:19:27,075 - INFO - Processing: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-11 00:19:27,075 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-11 00:19:27,075 - INFO - Processing: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-11 00:19:27,075 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-11 00:19:27,075 - INFO - Processing: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-11 00:19:27,076 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-11 00:19:27,076 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-11 00:19:27,104 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,105 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,105 - INFO - Extraindo metadados de: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-11 00:19:27,167 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,167 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,167 - INFO - Extraindo metadados de: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-11 00:19:27,199 - INFO - Processing: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-11 00:19:27,199 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-11 00:19:27,247 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,248 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,249 - INFO - Extraindo metadados de: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-11 00:19:27,251 - WARNING - Sem metadados: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-11 00:19:27,258 - INFO - Processing: /Users/menon/Downloads/bashcookbook.pdf
2024-11-11 00:19:27,258 - INFO - Sucesso: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-11 00:19:27,258 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/bashcookbook.pdf
2024-11-11 00:19:27,271 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,271 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,271 - INFO - Extraindo metadados de: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-11 00:19:27,305 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,305 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,305 - INFO - Extraindo metadados de: /Users/menon/Downloads/bashcookbook.pdf
2024-11-11 00:19:27,311 - INFO - Processing: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-11 00:19:27,311 - INFO - Sucesso: /Users/menon/Downloads/bashcookbook.pdf
2024-11-11 00:19:27,311 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-11 00:19:27,330 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,330 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,331 - INFO - Extraindo metadados de: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-11 00:19:27,345 - INFO - Processing: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-11 00:19:27,345 - WARNING - Sem metadados: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-11 00:19:27,345 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-11 00:19:27,379 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,379 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,380 - INFO - Extraindo metadados de: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-11 00:19:27,385 - INFO - Processing: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-11 00:19:27,385 - INFO - Sucesso: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-11 00:19:27,385 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-11 00:19:27,454 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,455 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,455 - INFO - Extraindo metadados de: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-11 00:19:27,482 - INFO - Processing: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-11 00:19:27,482 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-11 00:19:27,483 - WARNING - Sem metadados: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-11 00:19:27,523 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,524 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,524 - INFO - Extraindo metadados de: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-11 00:19:27,806 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,806 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,807 - INFO - Extraindo metadados de: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-11 00:19:27,824 - INFO - Processing: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-11 00:19:27,824 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-11 00:19:27,824 - INFO - Sucesso: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-11 00:19:27,912 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:27,912 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:27,912 - INFO - Extraindo metadados de: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-11 00:19:27,939 - INFO - Processing: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-11 00:19:27,939 - WARNING - Sem metadados: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-11 00:19:27,939 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-11 00:19:28,114 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:19:28,114 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:19:28,114 - INFO - Extraindo metadados de: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-11 00:19:28,121 - INFO - Sucesso: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-11 00:20:04,597 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781119895220/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:20:04,607 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586110340/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:20:04,685 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781593278755/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:20:36,861 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781593278755/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:20:36,897 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781119895220/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:20:36,967 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586110340/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:21:08,890 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781593278755/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:21:08,896 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586110340/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:21:08,983 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781119895220/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:21:12,069 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781119895220
2024-11-11 00:21:12,080 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781593278755
2024-11-11 00:21:12,081 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586110340
2024-11-11 00:21:12,297 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781119895220
2024-11-11 00:21:12,306 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586110340
2024-11-11 00:21:12,306 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781593278755
2024-11-11 00:21:12,577 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781119895220
2024-11-11 00:21:12,577 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586110340
2024-11-11 00:21:12,578 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781593278755
2024-11-11 00:21:33,942 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9baf70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:21:33,943 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9bad90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:21:33,943 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a2b9a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:21:34,948 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:21:34,951 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d13d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:21:34,953 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d14f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:21:36,956 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:21:36,957 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:21:36,957 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d16d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:21:40,963 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1be0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:21:40,964 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1d60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:21:40,964 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:21:48,975 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de2b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:21:48,976 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:21:48,976 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:21:48,983 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9786586110340 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de9a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:21:48,984 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781593278755 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9deac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:21:48,984 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781119895220 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:21:48,990 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9dee50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:21:48,990 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9ec310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:21:48,991 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9ec130>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:21:49,996 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9ec4c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:21:49,997 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9ec700>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:21:49,998 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9ec880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:21:52,000 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:21:52,002 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:21:52,003 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de4c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:21:56,004 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d17c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:21:56,006 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1fa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:21:56,009 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:22:04,014 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110340
2024-11-11 00:22:04,015 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781593278755
2024-11-11 00:22:04,015 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895220
2024-11-11 00:22:04,020 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781119895220 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9ece20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:22:04,020 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781593278755 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9ecd00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:22:04,020 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9786586110340 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9ecbb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:22:09,367 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9f6250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895220
2024-11-11 00:22:09,367 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9f6880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278755
2024-11-11 00:22:09,368 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9f68e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110340
2024-11-11 00:22:10,372 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9f6ee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895220
2024-11-11 00:22:10,376 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11aa01070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278755
2024-11-11 00:22:10,376 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11aa01160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110340
2024-11-11 00:22:12,381 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110340
2024-11-11 00:22:12,382 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895220
2024-11-11 00:22:12,384 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278755
2024-11-11 00:22:16,393 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1dc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895220
2024-11-11 00:22:16,394 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d17c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278755
2024-11-11 00:22:16,394 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9d1fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110340
2024-11-11 00:22:24,403 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de580>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781593278755
2024-11-11 00:22:24,404 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110340
2024-11-11 00:22:24,405 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11a9de160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895220
2024-11-11 00:22:24,411 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781593278755 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11aa01310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:22:24,411 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9786586110340 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11aa013d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:22:24,412 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781119895220 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11aa014f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:22:42,952 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781593278755 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:22:42,958 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9786586110340 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:22:43,226 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781119895220 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:23:02,761 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9786586110340 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:23:02,775 - INFO - Sucesso: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-11 00:23:02,790 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781119895220 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:23:02,796 - INFO - Sucesso: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-11 00:23:02,920 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781593278755 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:23:02,923 - INFO - Sucesso: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-11 00:23:46,529 - INFO - Extractores disponíveis: pypdf2, pdfplumber, pdfminer, tesseract, pdf2image
2024-11-11 00:23:46,530 - INFO - Suporte a OCR está disponível
2024-11-11 00:23:46,531 - INFO - Encontrados 12 arquivos PDF para processar
2024-11-11 00:23:46,531 - INFO - Processing: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-11 00:23:46,531 - INFO - Processing: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-11 00:23:46,531 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-11 00:23:46,531 - INFO - Processing: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-11 00:23:46,531 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-11 00:23:46,531 - INFO - Processing: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-11 00:23:46,532 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-11 00:23:46,532 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-11 00:23:46,559 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:23:46,559 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:23:46,560 - INFO - Extraindo metadados de: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-11 00:23:46,626 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:23:46,632 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:23:46,643 - INFO - Extraindo metadados de: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-11 00:23:46,657 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:23:46,657 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:23:46,657 - INFO - Extraindo metadados de: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-11 00:23:46,674 - INFO - Processing: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-11 00:23:46,674 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-11 00:23:46,685 - WARNING - Sem metadados: /Users/menon/Downloads/Hands-On Artificial Intelligence for Banking.pdf
2024-11-11 00:23:46,706 - INFO - Processing: /Users/menon/Downloads/bashcookbook.pdf
2024-11-11 00:23:46,706 - INFO - Sucesso: /Users/menon/Downloads/bugbountybootcamp.pdf
2024-11-11 00:23:46,706 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/bashcookbook.pdf
2024-11-11 00:23:46,726 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:23:46,726 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:23:46,726 - INFO - Extraindo metadados de: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-11 00:23:46,754 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:23:46,754 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:23:46,755 - INFO - Extraindo metadados de: /Users/menon/Downloads/bashcookbook.pdf
2024-11-11 00:23:46,759 - INFO - Processing: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-11 00:23:46,759 - INFO - Sucesso: /Users/menon/Downloads/bashcookbook.pdf
2024-11-11 00:23:46,759 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-11 00:23:46,778 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:23:46,779 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:23:46,779 - INFO - Extraindo metadados de: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-11 00:23:47,089 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:23:47,089 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:23:47,090 - INFO - Extraindo metadados de: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-11 00:23:47,104 - INFO - Processing: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-11 00:23:47,105 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-11 00:23:47,105 - INFO - Sucesso: /Users/menon/Downloads/python ciencia 00002cd9.pdf
2024-11-11 00:23:47,139 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:23:47,139 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:23:47,140 - INFO - Extraindo metadados de: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-11 00:23:47,143 - INFO - Processing: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-11 00:23:47,144 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-11 00:23:47,144 - INFO - Sucesso: /Users/menon/Downloads/javaperformance2ndedition.pdf
2024-11-11 00:23:47,207 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:23:47,208 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:23:47,208 - INFO - Extraindo metadados de: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-11 00:24:21,541 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781394158492/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:24:21,705 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781098109158/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:24:22,359 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586110357/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:24:22,460 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781119895213/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:24:52,529 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781394158492/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:24:52,645 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781098109158/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:24:53,240 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586110357/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:24:53,733 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781119895213/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:25:23,437 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781394158492/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:25:23,512 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781098109158/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:25:24,169 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9786586110357/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:25:24,382 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781394158492
2024-11-11 00:25:24,441 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781098109158
2024-11-11 00:25:24,609 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781394158492
2024-11-11 00:25:24,657 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781119895213/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:25:24,677 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781098109158
2024-11-11 00:25:24,838 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781394158492
2024-11-11 00:25:24,899 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781098109158
2024-11-11 00:25:25,089 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586110357
2024-11-11 00:25:25,312 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586110357
2024-11-11 00:25:25,539 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9786586110357
2024-11-11 00:25:25,597 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781119895213
2024-11-11 00:25:25,826 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781119895213
2024-11-11 00:25:26,052 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781119895213
2024-11-11 00:25:36,327 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff54b20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:25:36,362 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcbc790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:25:36,707 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcbcdc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:25:37,331 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcbc3d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:25:37,366 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fceb490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:25:37,437 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fef6c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:25:37,714 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fceb4f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:25:38,448 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fceb7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:25:39,339 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fceb550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:25:39,370 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fceb700>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:25:39,717 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcebd30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:25:40,454 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcebe20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:25:43,346 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf1490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:25:43,374 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf1070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:25:43,720 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf1fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:25:44,457 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf13d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:25:51,358 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf1e80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:25:51,367 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781394158492 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e4bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:25:51,374 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e4cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:25:51,379 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf1bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:25:51,381 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781098109158 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:25:51,386 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fea0550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:25:51,725 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf1340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:25:51,729 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781119895213 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcd3970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:25:51,737 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcd3d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:25:52,381 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98760>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:25:52,391 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fea0e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:25:52,462 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e4b20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:25:52,465 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9786586110357 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf1b20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:25:52,472 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf15b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:25:52,747 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcd3490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:25:53,480 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf12b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:25:54,397 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcd3340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:25:54,397 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcd3fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:25:54,754 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcf16a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:25:55,487 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcd3c40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:25:58,404 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcfb6d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:25:58,405 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcfb6a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:25:58,759 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcadc40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:25:59,491 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcadfa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:26:06,412 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcad5e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781394158492
2024-11-11 00:26:06,413 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcad7f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781098109158
2024-11-11 00:26:06,419 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781394158492 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcad400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:26:06,420 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781098109158 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcad430>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:26:06,762 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcadee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781119895213
2024-11-11 00:26:06,767 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781119895213 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fc65a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:26:07,500 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcadb50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9786586110357
2024-11-11 00:26:07,504 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9786586110357 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fc65cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:26:07,540 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fc65940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781394158492
2024-11-11 00:26:07,782 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fcad6a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895213
2024-11-11 00:26:08,195 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fc65b50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781098109158
2024-11-11 00:26:08,523 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fc65220>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110357
2024-11-11 00:26:08,544 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12818bfd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781394158492
2024-11-11 00:26:08,789 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12818bd30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895213
2024-11-11 00:26:09,200 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12818ba60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781098109158
2024-11-11 00:26:09,530 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12818b9a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110357
2024-11-11 00:26:10,549 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12818b790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781394158492
2024-11-11 00:26:10,796 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12818b520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895213
2024-11-11 00:26:11,206 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fc95280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781098109158
2024-11-11 00:26:11,533 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fc95790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110357
2024-11-11 00:26:14,554 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fc959a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781394158492
2024-11-11 00:26:14,801 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fc95ca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895213
2024-11-11 00:26:15,214 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12807ed00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781098109158
2024-11-11 00:26:15,561 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12807eee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110357
2024-11-11 00:26:22,567 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff1a100>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781394158492
2024-11-11 00:26:22,578 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781394158492 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff1a8b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:26:22,809 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff1a2e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781119895213
2024-11-11 00:26:22,811 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781119895213 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff1af10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:26:23,221 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff1a4c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781098109158
2024-11-11 00:26:23,225 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781098109158 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff158b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:26:23,567 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff1a6a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9786586110357
2024-11-11 00:26:23,570 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9786586110357 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff15f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:26:38,845 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781394158492 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:26:39,058 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781119895213 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:26:39,366 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781098109158 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:26:40,133 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9786586110357 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:26:55,910 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781394158492 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:26:55,921 - INFO - Processing: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-11 00:26:55,922 - INFO - Sucesso: /Users/menon/Downloads/softwaretransparency_supplychainsecurityinaneraofasoftware-drivens.pdf
2024-11-11 00:26:55,922 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-11 00:26:55,999 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:26:55,999 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:26:55,999 - INFO - Extraindo metadados de: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-11 00:26:56,002 - INFO - Processing: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-11 00:26:56,003 - INFO - Sucesso: /Users/menon/Downloads/hardwarehackinghandbook.pdf
2024-11-11 00:26:56,003 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-11 00:26:56,090 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:26:56,090 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:26:56,091 - INFO - Extraindo metadados de: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-11 00:26:56,091 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781119895213 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:26:56,097 - INFO - Processing: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-11 00:26:56,097 - INFO - Iniciando extração de texto de: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-11 00:26:56,097 - INFO - Sucesso: /Users/menon/Downloads/activedefender_immersionintheoffensivesecuritymindset.pdf
2024-11-11 00:26:56,322 - INFO - Métodos tentados: PyPDF2
2024-11-11 00:26:56,322 - INFO - Métodos bem-sucedidos: PyPDF2
2024-11-11 00:26:56,322 - INFO - Extraindo metadados de: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
2024-11-11 00:26:56,397 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781098109158 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:26:56,399 - INFO - Sucesso: /Users/menon/Downloads/ansible_upandrunning3rdedition.pdf
2024-11-11 00:26:56,531 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9786586110357 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:26:56,533 - INFO - Sucesso: /Users/menon/Downloads/computacao-evolucionaria-aplique-os-algoritmos-geneticos-com-python-e-numpy.pdf
2024-11-11 00:27:30,045 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781803237015/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:27:30,095 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781491957660/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:28:01,783 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781491957660/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:28:01,982 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781803237015/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:28:32,853 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781803237015/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:28:33,278 - ERROR - O'Reilly API error: HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /api/v2/book/isbn/9781491957660/ (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:28:33,787 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781803237015
2024-11-11 00:28:34,017 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781803237015
2024-11-11 00:28:34,217 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781491957660
2024-11-11 00:28:34,245 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781803237015
2024-11-11 00:28:34,446 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781491957660
2024-11-11 00:28:34,682 - ERROR - Springer API error: 403 Client Error: Forbidden for url: https://api.springernature.com/metadata/books/isbn/9781491957660
2024-11-11 00:28:47,056 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff94bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:28:47,057 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x128255880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:28:48,065 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12824df40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:28:48,066 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12824dee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:28:50,073 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fffdbb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:28:50,076 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1280af970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:28:54,083 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e4d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:28:54,085 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e4460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:29:02,097 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e4d60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:29:02,097 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e4b50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:29:02,102 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781803237015 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e4760>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:29:02,103 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781491957660 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e48e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:29:02,110 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1281e4670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:29:02,111 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff90160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:29:03,117 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98d60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:29:03,118 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:29:05,126 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe989d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:29:05,128 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:29:09,135 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:29:09,136 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98af0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:29:17,146 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98220>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781491957660
2024-11-11 00:29:17,147 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11feaf9a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/isbn/9781803237015
2024-11-11 00:29:17,153 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781491957660 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11febdca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:29:17,155 - ERROR - CBL API error: HTTPSConnectionPool(host='isbn.cbl.org.br', port=443): Max retries exceeded with url: /api/isbn/9781803237015 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11febd730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:29:19,219 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe27790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781803237015
2024-11-11 00:29:20,008 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11febd3a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491957660
2024-11-11 00:29:20,226 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe27a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781803237015
2024-11-11 00:29:21,015 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11feafa90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491957660
2024-11-11 00:29:22,235 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe985b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781803237015
2024-11-11 00:29:23,024 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe981f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491957660
2024-11-11 00:29:26,243 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781803237015
2024-11-11 00:29:27,032 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491957660
2024-11-11 00:29:34,250 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781803237015
2024-11-11 00:29:34,257 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781803237015 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:29:35,038 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fe98fa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /v1/search?q=isbn:9781491957660
2024-11-11 00:29:35,043 - ERROR - Zbib error: HTTPSConnectionPool(host='api.zbib.org', port=443): Max retries exceeded with url: /v1/search?q=isbn:9781491957660 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ff90340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-11-11 00:29:51,543 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781803237015 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:29:51,993 - ERROR - MyBib API error: HTTPSConnectionPool(host='www.mybib.com', port=443): Max retries exceeded with url: /api/v1/references?q=9781491957660 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:30:10,907 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781803237015 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:30:10,909 - ERROR - Ebook.de API error: HTTPSConnectionPool(host='www.ebook.de', port=443): Max retries exceeded with url: /de/tools/isbn2bibtex/9781491957660 (Caused by ResponseError('too many 404 error responses'))
2024-11-11 00:30:10,919 - INFO - Sucesso: /Users/menon/Downloads/appliedmachinelearningandhigh-performancecomputingonaws.pdf
2024-11-11 00:30:10,922 - INFO - Sucesso: /Users/menon/Downloads/pdfcoffee.com_python-para-analise-de-dados-wes-mckinney-pdf-free.pdf
